import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
const prisma = new PrismaClient();
const email = process.env.SEED_ADMIN_EMAIL?.trim().toLowerCase();
const password = process.env.SEED_ADMIN_PASSWORD;
if (!email || !password) throw new Error("Set SEED_ADMIN_EMAIL and SEED_ADMIN_PASSWORD to intentionally seed an admin.");
const passwordHash = await bcrypt.hash(password, 12);
await prisma.user.upsert({ where: { email }, update: {}, create: { email, passwordHash, name: process.env.SEED_ADMIN_NAME || "Wat Otrao Administrator", role: "SUPER_ADMIN", status: "ACTIVE" } });
await prisma.$disconnect();
