import { NavLink, Outlet, useLocation, useNavigate } from "react-router-dom";
import { useEffect, useMemo, useState } from "react";
import { isAdminDemoMode, useAuth } from "../context/AuthContext";
import { mockRows, mockPosts } from "../data/mockData";

const links = [["/", "ផ្ទាំងគ្រប់គ្រង"], ["/posts", "ព័ត៌មាន និងអត្ថបទ"], ["/categories", "ប្រភេទអត្ថបទ"], ["/activities", "សកម្មភាព"], ["/dharma", "ព្រះធម៌"], ["/events", "កម្មវិធី និងព្រឹត្តិការណ៍"], ["/monks", "ព្រះសង្ឃ"], ["/projects", "គម្រោងអភិវឌ្ឍន៍"], ["/gallery", "បណ្ណសាររូបភាព"], ["/media", "បណ្ណាល័យមេឌៀ"], ["/users", "អ្នកប្រើប្រាស់ និងតួនាទី"], ["/audit-logs", "ប្រវត្តិសកម្មភាព"], ["/settings", "ការកំណត់"]];
const searchable = [{ key: "posts", route: "/posts", label: "ព័ត៌មាន", rows: mockPosts }, ...["activities", "dharma", "events", "monks", "projects", "gallery", "media"].map((key) => ({ key, route: `/${key}`, label: key, rows: mockRows[key] || [] }))];

function Sidebar({ open, onClose }) { const { logout, user } = useAuth(); return <><div className={`sidebar-overlay ${open ? "show" : ""}`} onClick={onClose} /><aside className={`sidebar ${open ? "open" : ""}`}><div className="brand"><div className="brand-mark">វ</div><div><strong>វត្ត អូរត្រាវ</strong><small>ADMIN CMS</small></div><button aria-label="បិទម៉ឺនុយ" className="mobile-close" onClick={onClose}>×</button></div><nav>{links.map(([to, label], index) => <NavLink end={to === "/"} onClick={onClose} className={({ isActive }) => `nav-item ${isActive ? "active" : ""}`} to={to} key={to}><i>{index === 0 ? "▦" : "◈"}</i><span>{label}</span></NavLink>)}</nav><div className="sidebar-footer"><div className="mini-profile"><div className="avatar">A</div><div><strong>{user?.name || "Admin"}</strong><small>អ្នកគ្រប់គ្រង</small></div></div><button className="logout-link" onClick={logout}>↪ ចាកចេញ</button></div></aside></>; }

function SearchPanel({ onClose }) { const navigate = useNavigate(); const [query, setQuery] = useState(""); const results = useMemo(() => searchable.flatMap((group) => group.rows.filter((row) => Object.values(row).join(" ").toLowerCase().includes(query.toLowerCase())).slice(0, 4).map((row) => ({ ...row, route: group.route, group: group.label }))), [query]); useEffect(() => { const onKey = (e) => e.key === "Escape" && onClose(); window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [onClose]); return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={(e) => e.stopPropagation()}><div className="modal-head"><h2>ស្វែងរកក្នុង Admin CMS</h2><button aria-label="បិទការស្វែងរក" className="icon-btn" onClick={onClose}>×</button></div><input autoFocus className="search-input" style={{ width: "100%" }} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ស្វែងរកព័ត៌មាន សកម្មភាព ព្រះសង្ឃ..." /><div style={{ marginTop: 16 }}>{query && results.map((row) => <button key={`${row.group}-${row.id}`} onClick={() => { navigate(row.route); onClose(); }} style={{ display: "block", width: "100%", textAlign: "left", border: 0, borderBottom: "1px solid #eef0f5", background: "white", padding: "12px 4px" }}><strong>{row.title || row.name}</strong><small style={{ display: "block", color: "#8a90a5" }}>{row.group}</small></button>)}{query && !results.length && <div className="empty-state">មិនមានលទ្ធផលស្វែងរក</div>}</div></div></div>; }

function NotificationPanel({ onClose }) { const [items, setItems] = useState([{ id: 1, text: "មានអត្ថបទកំពុងរង់ចាំការពិនិត្យ", unread: true }, { id: 2, text: "ព្រឹត្តិការណ៍ថ្មីជិតមកដល់", unread: true }, { id: 3, text: "បានបង្កើតព្រាងថ្មី", unread: false }]); return <div style={{ position: "absolute", right: 70, top: 58, zIndex: 60, width: 300, background: "white", border: "1px solid #e5e7ef", borderRadius: 12, boxShadow: "0 14px 30px #10163b22", padding: 14 }}><div className="card-head"><h2>ការជូនដំណឹង</h2><button className="muted-link" onClick={() => setItems(items.map((x) => ({ ...x, unread: false })))}>អានទាំងអស់</button></div>{items.map((item) => <button key={item.id} onClick={() => setItems(items.map((x) => x.id === item.id ? { ...x, unread: false } : x))} style={{ display: "block", width: "100%", textAlign: "left", border: 0, background: item.unread ? "#f3f4ff" : "white", padding: 10, borderRadius: 7, marginBottom: 5, fontSize: 11 }}>{item.unread && "● "}{item.text}</button>)}<button className="muted-link" onClick={onClose}>បិទ</button></div>; }

export function AdminLayout() { const [open, setOpen] = useState(false); const [search, setSearch] = useState(false); const [notifications, setNotifications] = useState(false); const [profile, setProfile] = useState(false); const location = useLocation(); const navigate = useNavigate(); const { logout } = useAuth(); const title = links.find(([to]) => location.pathname === to || (to !== "/" && location.pathname.startsWith(to)))?.[1] || "ការគ្រប់គ្រង"; return <div className="admin-shell"><Sidebar open={open} onClose={() => setOpen(false)} /><div className="admin-main"><header className="topbar"><button aria-label="បើកម៉ឺនុយ" className="menu-btn" onClick={() => setOpen(true)}>☰</button><div className="crumb"><strong>{title}</strong><span>វត្ត អូរត្រាវ / Admin CMS</span></div><div className="top-actions" style={{ position: "relative" }}>{isAdminDemoMode && <span className="demo-badge">DEMO MODE</span>}<button aria-label="ស្វែងរក" className="top-icon" onClick={() => setSearch(true)}>⌕</button><button aria-label="ការជូនដំណឹង" className="top-icon notification" onClick={() => setNotifications(!notifications)}>♢<em>2</em></button><a aria-label="មើលគេហទំព័រសាធារណៈ" className="top-icon" href="http://localhost:3000" target="_blank" rel="noreferrer">↗</a><button aria-label="ម៉ឺនុយប្រវត្តិរូប" className="top-user" onClick={() => setProfile(!profile)}><div className="avatar">A</div><span>Admin</span><b>⌄</b></button>{notifications && <NotificationPanel onClose={() => setNotifications(false)} />}{profile && <div style={{ position: "absolute", right: 0, top: 50, zIndex: 60, background: "white", border: "1px solid #e5e7ef", borderRadius: 10, boxShadow: "0 14px 30px #10163b22", padding: 8, width: 180 }}><button className="quick-action" style={{ width: "100%" }} onClick={() => navigate("/profile")}>ប្រវត្តិរូប</button><button className="quick-action" style={{ width: "100%" }} onClick={() => navigate("/settings")}>ការកំណត់</button><button className="quick-action" style={{ width: "100%" }} onClick={logout}>ចាកចេញ</button></div>}</div></header><main className="content"><Outlet /></main></div>{search && <SearchPanel onClose={() => setSearch(false)} />}</div>; }
