import { useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Badge, Button, PageHeader, SearchInput } from "../components/ui";
import { mockRows, mockPosts } from "../data/mockData";

const config = { posts: { title: "ព័ត៌មាន និងអត្ថបទ", key: "posts", add: "/posts/new", columns: ["ចំណងជើង", "ប្រភេទ", "អ្នកនិពន្ធ", "ស្ថានភាព", "កាលបរិច្ឆេទ"] }, categories: { title: "ប្រភេទអត្ថបទ", key: "categories", add: null, columns: ["ឈ្មោះខ្មែរ", "ឈ្មោះអង់គ្លេស", "Slug", "ចំនួនអត្ថបទ", "ស្ថានភាព"] }, activities: { title: "សកម្មភាព", key: "activities", add: "/activities/new", columns: ["ចំណងជើង", "កាលបរិច្ឆេទ", "ទីតាំង", "ស្ថានភាព", "Featured"] }, dharma: { title: "ព្រះធម៌", key: "dharma", add: "/dharma/new", columns: ["ចំណងជើង", "ប្រភេទ", "ព្រះធម្មកថិក", "ស្ថានភាព", "កាលបរិច្ឆេទ"] }, events: { title: "កម្មវិធី និងព្រឹត្តិការណ៍", key: "events", add: "/events/new", columns: ["កម្មវិធី", "កាលបរិច្ឆេទ", "ទីតាំង", "ស្ថានភាព"] }, monks: { title: "ព្រះសង្ឃ", key: "monks", add: "/monks/new", columns: ["ព្រះនាមខ្មែរ", "English Name", "តួនាទី", "ស្ថានភាព"] }, projects: { title: "គម្រោងអភិវឌ្ឍន៍", key: "projects", add: "/projects/new", columns: ["គម្រោង", "វឌ្ឍនភាព", "ស្ថានភាព", "បញ្ចប់"] }, gallery: { title: "បណ្ណសាររូបភាព", key: "gallery", add: "/gallery/new", columns: ["អាល់ប៊ុម", "ចំនួនរូបភាព", "ស្ថានភាព", "កាលបរិច្ឆេទ"] }, media: { title: "បណ្ណាល័យមេឌៀ", key: "media", add: null, columns: ["ឯកសារ", "ប្រភេទ", "ទំហំ", "កាលបរិច្ឆេទ"] }, users: { title: "អ្នកប្រើប្រាស់ និងតួនាទី", key: "users", add: null, columns: ["ឈ្មោះ", "អ៊ីមែល", "តួនាទី", "ស្ថានភាព", "ចូលចុងក្រោយ"] }, "audit-logs": { title: "ប្រវត្តិសកម្មភាព", key: "audit", add: null, columns: ["អ្នកប្រើប្រាស់", "សកម្មភាព", "ម៉ូឌុល", "សេចក្ដីពិពណ៌នា", "កាលបរិច្ឆេទ"] } };

function statusTone(value) { return /ផ្សព្វផ្សាយ|សកម្ម|មកដល់|អនុវត្ត/.test(value) ? "success" : /ព្រាង|ពិនិត្យ|ប្រមូល/.test(value) ? "warning" : "info"; }
export function ModulePage({ name }) { const c = config[name] || config.posts; const [search, setSearch] = useState(""); const rows = name === "posts" ? mockPosts : mockRows[c.key] || []; const visible = useMemo(() => rows.filter((row) => Object.values(row).join(" ").toLowerCase().includes(search.toLowerCase())), [rows, search]); return <><PageHeader title={c.title} description="គ្រប់គ្រង និងរៀបចំមាតិកាសម្រាប់គេហទំព័រវត្តអូរត្រាវ" action={c.add && <Link className="btn btn-primary" to={c.add}>＋ បង្កើតថ្មី</Link>} /><section className="card table-card"><div className="table-toolbar"><SearchInput value={search} onChange={(e) => setSearch(e.target.value)} placeholder="ស្វែងរកក្នុងបញ្ជី..." /><select><option>ស្ថានភាពទាំងអស់</option><option>សកម្ម</option><option>ព្រាង</option></select><select><option>តម្រៀបតាមថ្មីបំផុត</option></select></div><div className="table-wrap"><table className="data-table"><thead><tr>{c.columns.map((x) => <th key={x}>{x}</th>)}<th>សកម្មភាព</th></tr></thead><tbody>{visible.map((row) => <tr key={row.id}>{Object.entries(row).filter(([key]) => key !== "id").slice(0, c.columns.length).map(([key, value]) => <td key={key}>{key === "status" ? <Badge tone={statusTone(value)}>{value}</Badge> : key === "progress" ? <div style={{ minWidth: 100 }}><div className="progress"><i style={{ width: `${value}%` }} /></div><small>{value}%</small></div> : value}</td>)}<td><div className="row-actions"><button>មើល</button><button>កែប្រែ</button><button>⋮</button></div></td></tr>)}</tbody></table></div>{visible.length === 0 && <div className="empty-state">មិនមានទិន្នន័យត្រូវនឹងការស្វែងរក</div>}</section></>; }

export function EditorPage({ name, id }) { const c = config[name] || config.posts; return <><PageHeader title={`${id ? "កែប្រែ" : "បង្កើត"} ${c.title}`} description="ទិន្នន័យនេះជាការបង្ហាញ UI ប៉ុណ្ណោះ មិនទាន់រក្សាទុកទៅ database" action={<Link className="btn btn-secondary" to={`/${name}`}>ត្រឡប់ក្រោយ</Link>} /><div className="editor-grid"><section className="card form-stack"><div className="field"><label>ចំណងជើងជាភាសាខ្មែរ</label><input placeholder="បញ្ចូលចំណងជើង..." /></div><div className="field"><label>ចំណងជើងជាភាសាអង់គ្លេស</label><input placeholder="English title" /></div><div className="field"><label>Slug</label><input placeholder="content-slug" /></div><div className="field"><label>ខ្លឹមសារ</label><textarea placeholder="សរសេរខ្លឹមសាររបស់អ្នកនៅទីនេះ..." /></div><div className="field"><label>សេចក្ដីសង្ខេប</label><textarea placeholder="សេចក្ដីសង្ខេបខ្លី" /></div></section><aside className="form-stack"><section className="card form-stack"><div className="field"><label>ស្ថានភាព</label><select><option>ព្រាង</option><option>បានផ្សព្វផ្សាយ</option><option>កំពុងពិនិត្យ</option></select></div><div className="field"><label>ប្រភេទ</label><select><option>ជ្រើសរើសប្រភេទ</option><option>ដំណឹង</option><option>ព្រះធម៌</option></select></div><div className="field"><label>អ្នកនិពន្ធ</label><input placeholder="Admin" /></div><label><input type="checkbox" /> Featured នៅទំព័រដើម</label><div className="file-drop">＋ អូសរូបភាពមកទីនេះ ឬចុចដើម្បីជ្រើសរើស</div></section><section className="card modal-actions"><Button variant="secondary">រក្សាទុកជាព្រាង</Button><Button>ផ្សព្វផ្សាយ</Button></section></aside></div></>; }
