import express from "express";
import cookieParser from "cookie-parser";
import cors from "cors";
import helmet from "helmet";
import rateLimit from "express-rate-limit";
import { env } from "./config/env.js";
import authRoutes from "./modules/auth/routes.js";
const app = express();
const allowedOrigins = new Set([env.frontendOrigin, env.adminOrigin]);
app.use(helmet());
app.use(cors({ origin: (origin, callback) => !origin || allowedOrigins.has(origin) ? callback(null, true) : callback(new Error("Origin not allowed")), credentials: true }));
app.use(express.json({ limit: "1mb" }));
app.use(cookieParser());
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 300 }));
const loginLimiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 10, standardHeaders: true, legacyHeaders: false });
app.use((req, res, next) => { if (["POST", "PUT", "PATCH", "DELETE"].includes(req.method) && req.path.startsWith("/api/") && req.get("origin") && !allowedOrigins.has(req.get("origin"))) return res.status(403).json({ error: "Origin not allowed" }); next(); });
app.get("/health", (_req, res) => res.json({ ok: true, service: "wat-otrao-api" }));
app.get("/api/v1", (_req, res) => res.json({ version: "v1", status: "foundation" }));
app.use("/api/v1/auth", loginLimiter, authRoutes);
app.use((err, _req, res, _next) => { console.error(err); res.status(500).json({ error: "Internal server error" }); });
export default app;
