import React, { useState } from "react";
import { Link } from "react-router-dom";

export function Button({ children, variant = "primary", ...props }) { return <button className={`btn btn-${variant}`} {...props}>{children}</button>; }
export function Badge({ children, tone = "default" }) { return <span className={`badge badge-${tone}`}>{children}</span>; }
export function PageHeader({ eyebrow = "ADMIN CMS", title, description, action }) { return <div className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div>; }
export function StatCard({ label, value, tone = "blue" }) { return <div className={`stat-card stat-${tone}`}><span>{label}</span><strong>{value}</strong><small>ធៀបនឹងខែមុន ↑</small></div>; }
export function SearchInput({ value, onChange, placeholder = "ស្វែងរក..." }) { return <input className="search-input" value={value} onChange={onChange} placeholder={`⌕  ${placeholder}`} />; }
export function EmptyState({ children = "មិនទាន់មានទិន្នន័យ" }) { return <div className="empty-state">{children}</div>; }
export function Modal({ open, title, onClose, children }) { if (!open) return null; return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={(e) => e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={onClose}>×</button></div>{children}</div></div>; }
export function LinkButton({ to, children }) { return <Link className="btn btn-primary" to={to}>{children}</Link>; }

export function LoadingState({ label = "កំពុងផ្ទុក..." }) { return <div className="empty-state" role="status">◌ {label}</div>; }
export function ErrorState({ message = "មានបញ្ហាក្នុងការបង្ហាញទិន្នន័យ" }) { return <div className="empty-state" role="alert" style={{ color: "#b6453e" }}>⚠ {message}</div>; }
export function PermissionDenied() { return <div className="empty-state" role="alert">អ្នកមិនមានសិទ្ធិចូលប្រើផ្នែកនេះទេ។</div>; }
export function Pagination({ page, pageCount, onChange }) { if (pageCount <= 1) return null; return <div className="pagination" aria-label="ទំព័រ">{Array.from({ length: pageCount }, (_, i) => i + 1).map((n) => <button className={n === page ? "active" : ""} key={n} onClick={() => onChange(n)}>{n}</button>)}</div>; }
export function ConfirmDialog({ open, title = "បញ្ជាក់សកម្មភាព", description = "សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ។", onCancel, onConfirm }) { if (!open) return null; return <div className="modal-backdrop" role="dialog" aria-modal="true" onMouseDown={onCancel}><div className="modal" onMouseDown={(e) => e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button aria-label="បិទ" className="icon-btn" onClick={onCancel}>×</button></div><p>{description}</p><div className="modal-actions"><Button variant="secondary" onClick={onCancel}>បោះបង់</Button><Button onClick={onConfirm}>បញ្ជាក់</Button></div></div></div>; }
export function ActionMenu({ children }) { return <details className="action-menu"><summary aria-label="សកម្មភាពបន្ថែម">⋮</summary><div>{children}</div></details>; }
export function MediaPicker({ open, multiple = false, onClose, onConfirm }) { const [selected, setSelected] = useState([]); const media = ["wat-otrao-main.jpg", "dharma-cover.jpg", "temple-gallery.jpg", "monk-portrait.jpg"]; if (!open) return null; const toggle = (item) => setSelected((items) => multiple ? (items.includes(item) ? items.filter((x) => x !== item) : [...items, item]) : [item]); return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal"><div className="modal-head"><h2>ជ្រើសរើសមេឌៀ</h2><button aria-label="បិទ" className="icon-btn" onClick={onClose}>×</button></div><SearchInput placeholder="ស្វែងរកមេឌៀ..." /><div className="media-picker-grid">{media.map((item) => <button className={selected.includes(item) ? "selected" : ""} key={item} onClick={() => toggle(item)}><div className="media-placeholder">▧</div><small>{item}</small></button>)}</div><div className="modal-actions"><Button variant="secondary" onClick={onClose}>បោះបង់</Button><Button disabled={!selected.length} onClick={() => onConfirm(selected)}>ជ្រើសរើស ({selected.length})</Button></div></div></div>; }

export function ToastProvider({ children }) { const [toasts, setToasts] = useState([]); const notify = (message, tone = "success") => { const id = Date.now(); setToasts((items) => [...items, { id, message, tone }]); window.setTimeout(() => setToasts((items) => items.filter((item) => item.id !== id)), 3500); }; return <ToastContext.Provider value={notify}>{children}<div className="toast-stack" aria-live="polite">{toasts.map((toast) => <div className={`toast toast-${toast.tone}`} key={toast.id}>{toast.message}<button aria-label="បិទការជូនដំណឹង" onClick={() => setToasts((items) => items.filter((item) => item.id !== toast.id))}>×</button></div>)}</div></ToastContext.Provider>; }
const ToastContext = React.createContext(() => {});
export function useToast() { return React.useContext(ToastContext); }
